package Form;

import Form.UvodnyPanelForm;
import Form.PridatInstruktoraDialog;
import Form.ObsadenyInstruktorDialog;
import Dao.InstruktorDao;
import javax.swing.ImageIcon;
import sk.upjs.ics.lyz_skola.AkreditaciaComboBoxModel;
import sk.upjs.ics.lyz_skola.ObjectFactory;
import sk.upjs.ics.lyz_skola.TypComboBoxModel;

public class InstruktoriForm extends javax.swing.JFrame {

    private UvodnyPanelForm uvodnyPanel;
    private InstruktorDao instruktorDao = ObjectFactory.INSTANCE.getInstruktorDao();  
    private Integer vstupZoznam;
    private String priezvisko = null;
    private String akreditacia = null;
    private String typ = null;
    private Long id = -1L;
    
    public InstruktoriForm() {
        
    }
    
    public InstruktoriForm(UvodnyPanelForm uvodnyPanel){
        initComponents();
        this.uvodnyPanel = uvodnyPanel;
        vstupZoznam = 0;
        this.aktualizovatZoznam();
    }
    
    private void aktualizovatZoznam(){
        InstruktoriTableModel instruktoriModel = (InstruktoriTableModel) instruktoriTable.getModel();
        instruktoriModel.aktualizovat(vstupZoznam, priezvisko, akreditacia, typ);
    }  

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        instruktoriTable = new javax.swing.JTable();
        spatButton = new javax.swing.JButton();
        zoradPodlaPriezviskaButton = new javax.swing.JButton();
        zadajAkreditaciuLabel = new javax.swing.JLabel();
        vypisPodlaAkreditacieButton = new javax.swing.JButton();
        zadajTypLabel = new javax.swing.JLabel();
        vypisPodlaTypuButton = new javax.swing.JButton();
        pridatInstruktoraButton = new javax.swing.JButton();
        akreditaciaComboBox = new javax.swing.JComboBox<>();
        typComboBox = new javax.swing.JComboBox<>();
        vypisPodlaPriezviskaButton = new javax.swing.JButton();
        priezviskoTextField = new javax.swing.JTextField();
        zadajPriezviskoLabel = new javax.swing.JLabel();
        zmazatButton = new javax.swing.JButton();
        editTypButton = new javax.swing.JButton();
        editAkreditaciaButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setLocation(new java.awt.Point(300, 150));
        setPreferredSize(new java.awt.Dimension(810, 499));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        instruktoriTable.setModel(new InstruktoriTableModel());
        instruktoriTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                instruktoriTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(instruktoriTable);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(214, 11, 580, 425));

        spatButton.setText("Späť");
        spatButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                spatButtonActionPerformed(evt);
            }
        });
        getContentPane().add(spatButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 63, 174, -1));

        zoradPodlaPriezviskaButton.setText("Zoraď podľa priezviska");
        zoradPodlaPriezviskaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zoradPodlaPriezviskaButtonActionPerformed(evt);
            }
        });
        getContentPane().add(zoradPodlaPriezviskaButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(214, 447, 174, -1));

        zadajAkreditaciuLabel.setText("Zadaj akreditáciu:");
        getContentPane().add(zadajAkreditaciuLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 269, -1, 23));

        vypisPodlaAkreditacieButton.setText("Vypíš podľa akreditácie");
        vypisPodlaAkreditacieButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vypisPodlaAkreditacieButtonActionPerformed(evt);
            }
        });
        getContentPane().add(vypisPodlaAkreditacieButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 303, 174, -1));

        zadajTypLabel.setText("Zadaj typ:");
        getContentPane().add(zadajTypLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 158, -1, -1));

        vypisPodlaTypuButton.setText("Vypíš podľa typu");
        vypisPodlaTypuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vypisPodlaTypuButtonActionPerformed(evt);
            }
        });
        getContentPane().add(vypisPodlaTypuButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 188, 174, -1));

        pridatInstruktoraButton.setText("Pridaj inštruktora");
        pridatInstruktoraButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pridatInstruktoraButtonActionPerformed(evt);
            }
        });
        getContentPane().add(pridatInstruktoraButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 27, 174, -1));

        akreditaciaComboBox.setModel(new AkreditaciaComboBoxModel());
        getContentPane().add(akreditaciaComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(134, 270, 50, -1));

        typComboBox.setModel(new TypComboBoxModel());
        getContentPane().add(typComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(84, 154, 100, 23));

        vypisPodlaPriezviskaButton.setText("Vypíš podľa priezviska");
        vypisPodlaPriezviskaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vypisPodlaPriezviskaButtonActionPerformed(evt);
            }
        });
        getContentPane().add(vypisPodlaPriezviskaButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 447, 174, -1));

        priezviskoTextField.setText("Priezvisko");
        priezviskoTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                priezviskoTextFieldActionPerformed(evt);
            }
        });
        getContentPane().add(priezviskoTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 416, 174, -1));

        zadajPriezviskoLabel.setText("  Zadaj priezvisko:");
        getContentPane().add(zadajPriezviskoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 387, -1, 23));

        zmazatButton.setText("Zmazať inštruktora");
        zmazatButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zmazatButtonActionPerformed(evt);
            }
        });
        getContentPane().add(zmazatButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(654, 447, 140, -1));

        editTypButton.setText("Edit Typ");
        editTypButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editTypButtonActionPerformed(evt);
            }
        });
        getContentPane().add(editTypButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 217, 174, -1));

        editAkreditaciaButton.setText("Edit Akreditácia");
        editAkreditaciaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editAkreditaciaButtonActionPerformed(evt);
            }
        });
        getContentPane().add(editAkreditaciaButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 332, 174, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Silvia\\Desktop\\obrazky NETBeans\\Instrukt.jpg")); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-6, -16, 830, 530));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void spatButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_spatButtonActionPerformed
        this.dispose();
        uvodnyPanel.setVisible(true);
    }//GEN-LAST:event_spatButtonActionPerformed

    private void pridatInstruktoraButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pridatInstruktoraButtonActionPerformed
        PridatInstruktoraDialog pridatInstruktoraDialog = new PridatInstruktoraDialog(this, true);
        pridatInstruktoraDialog.setVisible(true);
        vstupZoznam = 0;
        aktualizovatZoznam();
    }//GEN-LAST:event_pridatInstruktoraButtonActionPerformed

    private void zoradPodlaPriezviskaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zoradPodlaPriezviskaButtonActionPerformed
        vstupZoznam = 1;
        aktualizovatZoznam();
    }//GEN-LAST:event_zoradPodlaPriezviskaButtonActionPerformed

    private void vypisPodlaTypuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vypisPodlaTypuButtonActionPerformed
        // TODO add your handling code here:
        typ = (String) typComboBox.getSelectedItem();
        vstupZoznam = 4;
        aktualizovatZoznam();
        
    }//GEN-LAST:event_vypisPodlaTypuButtonActionPerformed

    private void vypisPodlaAkreditacieButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vypisPodlaAkreditacieButtonActionPerformed
        // TODO add your handling code here:
        akreditacia = (String) akreditaciaComboBox.getSelectedItem();
        vstupZoznam = 3;
        aktualizovatZoznam();
    }//GEN-LAST:event_vypisPodlaAkreditacieButtonActionPerformed

    private void vypisPodlaPriezviskaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vypisPodlaPriezviskaButtonActionPerformed
        priezvisko = priezviskoTextField.getText();
        vstupZoznam = 2;
        aktualizovatZoznam();
    }//GEN-LAST:event_vypisPodlaPriezviskaButtonActionPerformed

    private void priezviskoTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_priezviskoTextFieldActionPerformed
        if(priezviskoTextField.getText().equals("Priezvisko")){
            priezviskoTextField.setText("");
        }
    }//GEN-LAST:event_priezviskoTextFieldActionPerformed

    private void zmazatButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zmazatButtonActionPerformed
        if(id != -1L){
            if(instruktorDao.nemaHodinu(id)){
                instruktorDao.vymazInstruktora(id);
                vstupZoznam = 0;
                aktualizovatZoznam();
            }else{
                ObsadenyInstruktorDialog obsadeny = new ObsadenyInstruktorDialog(this, true);
                obsadeny.setVisible(true);
            }  
        }
        id = -1L;
    }//GEN-LAST:event_zmazatButtonActionPerformed

    private void instruktoriTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_instruktoriTableMouseClicked
        id = (Long) instruktoriTable.getModel().getValueAt(instruktoriTable.getSelectedRow(), 5);
    }//GEN-LAST:event_instruktoriTableMouseClicked

    private void editTypButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editTypButtonActionPerformed
        if(id != -1L){
           typ = (String) typComboBox.getSelectedItem();
           instruktorDao.aktualizujTyp(id, typ);
           vstupZoznam = 0;
           aktualizovatZoznam();
        }
        id = -1L;
    }//GEN-LAST:event_editTypButtonActionPerformed

    private void editAkreditaciaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editAkreditaciaButtonActionPerformed
        if(id != -1L){
           typ = (String) akreditaciaComboBox.getSelectedItem();
           instruktorDao.aktualizujAkreditaciu(id, akreditacia);
           vstupZoznam = 0;
           aktualizovatZoznam();            
        }
        id = -1L;
    }//GEN-LAST:event_editAkreditaciaButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> akreditaciaComboBox;
    private javax.swing.JButton editAkreditaciaButton;
    private javax.swing.JButton editTypButton;
    private javax.swing.JTable instruktoriTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton pridatInstruktoraButton;
    private javax.swing.JTextField priezviskoTextField;
    private javax.swing.JButton spatButton;
    private javax.swing.JComboBox<String> typComboBox;
    private javax.swing.JButton vypisPodlaAkreditacieButton;
    private javax.swing.JButton vypisPodlaPriezviskaButton;
    private javax.swing.JButton vypisPodlaTypuButton;
    private javax.swing.JLabel zadajAkreditaciuLabel;
    private javax.swing.JLabel zadajPriezviskoLabel;
    private javax.swing.JLabel zadajTypLabel;
    private javax.swing.JButton zmazatButton;
    private javax.swing.JButton zoradPodlaPriezviskaButton;
    // End of variables declaration//GEN-END:variables
}
