package Form;

import Dao.HodinaDao;
import Form.UvodnyPanelForm;
import Form.PridatInstruktoraDialog;
import Form.ObsadenyInstruktorDialog;
import Dao.InstruktorDao;
import Entity.Instruktor;
import javax.swing.ImageIcon;
import sk.upjs.ics.lyz_skola.AkreditaciaComboBoxModel;
import sk.upjs.ics.lyz_skola.ObjectFactory;
import sk.upjs.ics.lyz_skola.TypComboBoxModel;

public class InstruktoriForm extends javax.swing.JFrame {

    private UvodnyPanelForm uvodnyPanel;
    private InstruktorDao instruktorDao = ObjectFactory.INSTANCE.getInstruktorDao(); 
    private HodinaDao hodinaDao = ObjectFactory.INSTANCE.getHodinaDao();
    private Integer vstupZoznam;
    private String priezvisko = null;
    private String akreditacia = null;
    private String typ = null;
    private Long id = -1L;
    
    public InstruktoriForm() {
        
    }
    
    public InstruktoriForm(UvodnyPanelForm uvodnyPanel){
        initComponents();
        this.uvodnyPanel = uvodnyPanel;
        vstupZoznam = 0;
        this.aktualizovatZoznam();
    }
    
    private void aktualizovatZoznam(){
        InstruktoriTableModel instruktoriModel = (InstruktoriTableModel) instruktoriTable.getModel();
        instruktoriModel.aktualizovat(vstupZoznam, priezvisko, akreditacia, typ);
    }  

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        instruktoriTable = new javax.swing.JTable();
        spatButton = new javax.swing.JButton();
        zoradPodlaPriezviskaButton = new javax.swing.JButton();
        zadajAkreditaciuLabel = new javax.swing.JLabel();
        vypisPodlaAkreditacieButton = new javax.swing.JButton();
        zadajTypLabel = new javax.swing.JLabel();
        vypisPodlaTypuButton = new javax.swing.JButton();
        pridatInstruktoraButton = new javax.swing.JButton();
        akreditaciaComboBox = new javax.swing.JComboBox<>();
        typComboBox = new javax.swing.JComboBox<>();
        vypisPodlaPriezviskaButton = new javax.swing.JButton();
        priezviskoTextField = new javax.swing.JTextField();
        zmazatButton = new javax.swing.JButton();
        editTypButton = new javax.swing.JButton();
        editAkreditaciaButton = new javax.swing.JButton();
        oduceneHodinyButton = new javax.swing.JButton();
        oduceneHodinyTextField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setLocation(new java.awt.Point(300, 150));
        setPreferredSize(new java.awt.Dimension(850, 500));
        setResizable(false);

        instruktoriTable.setModel(new InstruktoriTableModel());
        instruktoriTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                instruktoriTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(instruktoriTable);

        spatButton.setText("Späť");
        spatButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                spatButtonActionPerformed(evt);
            }
        });

        zoradPodlaPriezviskaButton.setText("Zoraď podľa priezviska");
        zoradPodlaPriezviskaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zoradPodlaPriezviskaButtonActionPerformed(evt);
            }
        });

        zadajAkreditaciuLabel.setText("Zadaj akreditáciu:");

        vypisPodlaAkreditacieButton.setText("Vypíš podľa akreditácie");
        vypisPodlaAkreditacieButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vypisPodlaAkreditacieButtonActionPerformed(evt);
            }
        });

        zadajTypLabel.setText("Zadaj typ:");

        vypisPodlaTypuButton.setText("Vypíš podľa typu");
        vypisPodlaTypuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vypisPodlaTypuButtonActionPerformed(evt);
            }
        });

        pridatInstruktoraButton.setText("Pridaj inštruktora");
        pridatInstruktoraButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pridatInstruktoraButtonActionPerformed(evt);
            }
        });

        akreditaciaComboBox.setModel(new AkreditaciaComboBoxModel());

        typComboBox.setModel(new TypComboBoxModel());

        vypisPodlaPriezviskaButton.setText("Vypíš podľa priezviska");
        vypisPodlaPriezviskaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vypisPodlaPriezviskaButtonActionPerformed(evt);
            }
        });

        priezviskoTextField.setText("Priezvisko");
        priezviskoTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                priezviskoTextFieldActionPerformed(evt);
            }
        });

        zmazatButton.setText("Zmazať inštruktora");
        zmazatButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zmazatButtonActionPerformed(evt);
            }
        });

        editTypButton.setText("Edit Typ");
        editTypButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editTypButtonActionPerformed(evt);
            }
        });

        editAkreditaciaButton.setText("Edit Akreditácia");
        editAkreditaciaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editAkreditaciaButtonActionPerformed(evt);
            }
        });

        oduceneHodinyButton.setText("Odučené hodiny inštruktora");
        oduceneHodinyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oduceneHodinyButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(vypisPodlaPriezviskaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(pridatInstruktoraButton, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(spatButton, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(zadajAkreditaciuLabel)
                                            .addGap(38, 38, 38)
                                            .addComponent(akreditaciaComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(priezviskoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addComponent(zadajTypLabel)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(typComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(vypisPodlaTypuButton, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(editTypButton, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(vypisPodlaAkreditacieButton, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(editAkreditaciaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(30, 30, 30)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(oduceneHodinyButton)
                                        .addGap(18, 18, 18)
                                        .addComponent(oduceneHodinyTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(zmazatButton, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 580, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(zoradPodlaPriezviskaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(56, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pridatInstruktoraButton)
                        .addGap(13, 13, 13)
                        .addComponent(spatButton)
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(typComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(zadajTypLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(vypisPodlaTypuButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(editTypButton)
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(akreditaciaComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(zadajAkreditaciuLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(vypisPodlaAkreditacieButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(editAkreditaciaButton)
                        .addGap(15, 15, 15))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(zmazatButton)
                    .addComponent(priezviskoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(oduceneHodinyButton)
                    .addComponent(oduceneHodinyTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(vypisPodlaPriezviskaButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(zoradPodlaPriezviskaButton)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void spatButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_spatButtonActionPerformed
        this.dispose();
        uvodnyPanel.setVisible(true);
    }//GEN-LAST:event_spatButtonActionPerformed

    private void pridatInstruktoraButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pridatInstruktoraButtonActionPerformed
        PridatInstruktoraDialog pridatInstruktoraDialog = new PridatInstruktoraDialog(this, true);
        pridatInstruktoraDialog.setVisible(true);
        vstupZoznam = 0;
        aktualizovatZoznam();
    }//GEN-LAST:event_pridatInstruktoraButtonActionPerformed

    private void zoradPodlaPriezviskaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zoradPodlaPriezviskaButtonActionPerformed
        vstupZoznam = 1;
        aktualizovatZoznam();
    }//GEN-LAST:event_zoradPodlaPriezviskaButtonActionPerformed

    private void vypisPodlaTypuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vypisPodlaTypuButtonActionPerformed
        // TODO add your handling code here:
        typ = (String) typComboBox.getSelectedItem();
        vstupZoznam = 4;
        aktualizovatZoznam();
        
    }//GEN-LAST:event_vypisPodlaTypuButtonActionPerformed

    private void vypisPodlaAkreditacieButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vypisPodlaAkreditacieButtonActionPerformed
        // TODO add your handling code here:
        akreditacia = (String) akreditaciaComboBox.getSelectedItem();
        vstupZoznam = 3;
        aktualizovatZoznam();
    }//GEN-LAST:event_vypisPodlaAkreditacieButtonActionPerformed

    private void vypisPodlaPriezviskaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vypisPodlaPriezviskaButtonActionPerformed
        priezvisko = priezviskoTextField.getText();
        vstupZoznam = 2;
        aktualizovatZoznam();
    }//GEN-LAST:event_vypisPodlaPriezviskaButtonActionPerformed

    private void priezviskoTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_priezviskoTextFieldActionPerformed
        if(priezviskoTextField.getText().equals("Priezvisko")){
            priezviskoTextField.setText("");
        }
    }//GEN-LAST:event_priezviskoTextFieldActionPerformed

    private void zmazatButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zmazatButtonActionPerformed
        if(id != -1L){
            if(instruktorDao.nemaHodinu(id)){
                instruktorDao.vymazInstruktora(id);
                vstupZoznam = 0;
                aktualizovatZoznam();
            }else{
                ObsadenyInstruktorDialog obsadeny = new ObsadenyInstruktorDialog(this, true);
                obsadeny.setVisible(true);
            }  
        }
        id = -1L;
    }//GEN-LAST:event_zmazatButtonActionPerformed

    private void instruktoriTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_instruktoriTableMouseClicked
        id = (Long) instruktoriTable.getModel().getValueAt(instruktoriTable.getSelectedRow(), 5);
    }//GEN-LAST:event_instruktoriTableMouseClicked

    private void editTypButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editTypButtonActionPerformed
        if(id != -1L){
           typ = (String) typComboBox.getSelectedItem();
           instruktorDao.aktualizujTyp(id, typ);
           vstupZoznam = 0;
           aktualizovatZoznam();
        }
        id = -1L;
    }//GEN-LAST:event_editTypButtonActionPerformed

    private void editAkreditaciaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editAkreditaciaButtonActionPerformed
        if(id != -1L){
           typ = (String) akreditaciaComboBox.getSelectedItem();
           instruktorDao.aktualizujAkreditaciu(id, akreditacia);
           vstupZoznam = 0;
           aktualizovatZoznam();            
        }
        id = -1L;
    }//GEN-LAST:event_editAkreditaciaButtonActionPerformed

    private void oduceneHodinyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oduceneHodinyButtonActionPerformed
        if(id != -1L){
           Instruktor instruktor = instruktorDao.podlaId(id);
           Long hodiny = hodinaDao.oduceneInstruktHodiny(instruktor);
           oduceneHodinyTextField.setText(hodiny.toString());
        }
        id = -1L;
    }//GEN-LAST:event_oduceneHodinyButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> akreditaciaComboBox;
    private javax.swing.JButton editAkreditaciaButton;
    private javax.swing.JButton editTypButton;
    private javax.swing.JTable instruktoriTable;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton oduceneHodinyButton;
    private javax.swing.JTextField oduceneHodinyTextField;
    private javax.swing.JButton pridatInstruktoraButton;
    private javax.swing.JTextField priezviskoTextField;
    private javax.swing.JButton spatButton;
    private javax.swing.JComboBox<String> typComboBox;
    private javax.swing.JButton vypisPodlaAkreditacieButton;
    private javax.swing.JButton vypisPodlaPriezviskaButton;
    private javax.swing.JButton vypisPodlaTypuButton;
    private javax.swing.JLabel zadajAkreditaciuLabel;
    private javax.swing.JLabel zadajTypLabel;
    private javax.swing.JButton zmazatButton;
    private javax.swing.JButton zoradPodlaPriezviskaButton;
    // End of variables declaration//GEN-END:variables
}
