package Form;

import Dao.HodinaDao;
import Entity.Hodina;
import java.awt.Color;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Scanner;
import sk.upjs.ics.lyz_skola.ObjectFactory;

public class UvodnyPanelForm extends javax.swing.JFrame {

    private String nastavenyDatum;
    private Long id = -1L;
    private HodinaDao hodinaDao = ObjectFactory.INSTANCE.getHodinaDao();

    public UvodnyPanelForm() {
        initComponents();
        nastavenyDatum = null;
        aktualizovatUvodnyPanel();
            
    }
    private void aktualizovatUvodnyPanel() {
        HodinyTableModel model = (HodinyTableModel) hodinyTable.getModel();                
        model.aktualizovat(nastavenyDatum);
    }
    
    private boolean kontrolaDatumu(String datum){
        boolean vystup = true;
        Scanner scan = new Scanner(datum).useDelimiter("-");
        while(scan.hasNext()){
            if(scan.hasNextInt()){
		scan.next();
            }else{
		vystup = false;
		scan.next();
            }
	}
        scan.close();
        return vystup;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        hodinyTable = new javax.swing.JTable();
        vyucbaButton = new javax.swing.JButton();
        instruktoriButton = new javax.swing.JButton();
        zakazniciButton = new javax.swing.JButton();
        datumButton = new javax.swing.JButton();
        vlozDatumTextField = new javax.swing.JTextField();
        formatDatumuLabel = new javax.swing.JLabel();
        zmazatHodinuButton = new javax.swing.JButton();
        prihlaseniaButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 204, 255));
        setForeground(java.awt.Color.red);
        setLocation(new java.awt.Point(300, 150));
        setPreferredSize(new java.awt.Dimension(810, 500));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        hodinyTable.setModel(new HodinyTableModel());
        hodinyTable.setOpaque(false);
        hodinyTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                hodinyTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(hodinyTable);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(195, 33, 580, 340));

        vyucbaButton.setText("Výučba");
        vyucbaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vyucbaButtonActionPerformed(evt);
            }
        });
        getContentPane().add(vyucbaButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 100, -1));

        instruktoriButton.setText("Inštruktori");
        instruktoriButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                instruktoriButtonActionPerformed(evt);
            }
        });
        getContentPane().add(instruktoriButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 147, 100, -1));

        zakazniciButton.setText("Zákazníci");
        zakazniciButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zakazniciButtonActionPerformed(evt);
            }
        });
        getContentPane().add(zakazniciButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 224, 100, -1));

        datumButton.setText("Dátum");
        datumButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                datumButtonActionPerformed(evt);
            }
        });
        getContentPane().add(datumButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(195, 391, 100, -1));

        vlozDatumTextField.setText("- - Vlozte datum - -");
        vlozDatumTextField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                vlozDatumTextFieldMouseClicked(evt);
            }
        });
        getContentPane().add(vlozDatumTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(313, 392, 142, -1));

        formatDatumuLabel.setText("\"yyyy-MM-dd\"");
        getContentPane().add(formatDatumuLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(313, 420, 90, -1));

        zmazatHodinuButton.setText("Zmazať hodinu");
        zmazatHodinuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zmazatHodinuButtonActionPerformed(evt);
            }
        });
        getContentPane().add(zmazatHodinuButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(633, 391, 142, -1));

        prihlaseniaButton.setText("Záznam prihlásení");
        prihlaseniaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prihlaseniaButtonActionPerformed(evt);
            }
        });
        getContentPane().add(prihlaseniaButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(633, 442, 142, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Silvia\\Desktop\\obrazky NETBeans\\uvodnyP.jpg")); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 830, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void vyucbaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vyucbaButtonActionPerformed
        this.setVisible(false);
        VyucbaForm vyucbaForm = new VyucbaForm(this);
        vyucbaForm.setVisible(true);
        aktualizovatUvodnyPanel();
    }//GEN-LAST:event_vyucbaButtonActionPerformed

    private void instruktoriButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_instruktoriButtonActionPerformed
        this.setVisible(false);
        InstruktoriForm instruktoriForm = new InstruktoriForm(this);
        instruktoriForm.setVisible(true);
    }//GEN-LAST:event_instruktoriButtonActionPerformed

    private void zakazniciButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zakazniciButtonActionPerformed
        this.setVisible(false);
        ZakazniciForm zakazniciForm = new ZakazniciForm(this);
        zakazniciForm.setVisible(true);
    }//GEN-LAST:event_zakazniciButtonActionPerformed

    private void datumButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_datumButtonActionPerformed
        nastavenyDatum = vlozDatumTextField.getText();
        boolean spravnost = true;
        Date datum;
        DateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        try {
            datum = dateFormat.parse(nastavenyDatum);
        } catch (Exception e) {
            spravnost = false;
        }
        if(spravnost){
            if(kontrolaDatumu(nastavenyDatum)){
                aktualizovatUvodnyPanel();
            }else{
                NespravneUdajeDialog vynimka = new NespravneUdajeDialog(this, true);
                vynimka.setVisible(true);
            }
        }else{
            NespravneUdajeDialog vynimka = new NespravneUdajeDialog(this, true);
            vynimka.setVisible(true);
        }
    }//GEN-LAST:event_datumButtonActionPerformed

    private void zmazatHodinuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zmazatHodinuButtonActionPerformed
        if(id != -1L){
            hodinaDao.vymazHodinu(id);
            this.aktualizovatUvodnyPanel();
        }
        id = -1L;
    }//GEN-LAST:event_zmazatHodinuButtonActionPerformed

    private void hodinyTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hodinyTableMouseClicked
        HodinyTableModel model = (HodinyTableModel) hodinyTable.getModel();                
        Hodina hodina = model.vratHodinu(hodinyTable.getSelectedRow());
        
        id = hodina.getId();                
        if(evt.getClickCount() == 2){
            if(hodina.isStav()){
                hodina.setStav(false);
            }else{
                hodina.setStav(true);
            }
            hodinaDao.zmenaStavu(hodina);
            aktualizovatUvodnyPanel();
        }
    }//GEN-LAST:event_hodinyTableMouseClicked

    private void vlozDatumTextFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_vlozDatumTextFieldMouseClicked
        if(vlozDatumTextField.getText().equals("- - Vlozte datum - -")){
            vlozDatumTextField.setText("");
    }
    }//GEN-LAST:event_vlozDatumTextFieldMouseClicked

    private void prihlaseniaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prihlaseniaButtonActionPerformed
        ZaznamPrihlaseniDialog prihlasenia = new ZaznamPrihlaseniDialog(this, true);
        prihlasenia.setVisible(true);
    }//GEN-LAST:event_prihlaseniaButtonActionPerformed

    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton datumButton;
    private javax.swing.JLabel formatDatumuLabel;
    private javax.swing.JTable hodinyTable;
    private javax.swing.JButton instruktoriButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton prihlaseniaButton;
    private javax.swing.JTextField vlozDatumTextField;
    private javax.swing.JButton vyucbaButton;
    private javax.swing.JButton zakazniciButton;
    private javax.swing.JButton zmazatHodinuButton;
    // End of variables declaration//GEN-END:variables
}
