package Form;

import Dao.HodinaDao;
import Entity.Zakaznik;
import Entity.Instruktor;
import Entity.Hodina;
import java.awt.HeadlessException;
import java.sql.Time;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import java.util.Scanner;
import sk.upjs.ics.lyz_skola.InstruktorComboBoxModel;
import sk.upjs.ics.lyz_skola.ObjectFactory;
import sk.upjs.ics.lyz_skola.ZakaznikComboBoxModel;

public class VyucbaForm extends javax.swing.JFrame {

    private UvodnyPanelForm uvodnyPanel;
    private HodinaDao hodinaDao = ObjectFactory.INSTANCE.getHodinaDao();

    public VyucbaForm(){
    
    }
   
    public VyucbaForm(UvodnyPanelForm uvodnyPanel) {
        initComponents();
        this.uvodnyPanel = uvodnyPanel;
    }
    
    private boolean kontrolaDatumu(String datum){
        boolean vystup = true;
        Scanner scan = new Scanner(datum).useDelimiter("-");
        while(scan.hasNext()){
            if(scan.hasNextInt()){
		scan.next();
            }else{
		vystup = false;
		scan.next();
            }
	}
        scan.close();
        return vystup;
    }
    
    private boolean kontrolaCasu(String cas){
        boolean vystup = true;
        Scanner scan = new Scanner(cas).useDelimiter(":");
        while(scan.hasNext()){
            if(scan.hasNextInt()){
		scan.next();
            }else{
		vystup = false;
		scan.next();
            }
	}
        scan.close();
        return vystup;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        odTextField = new javax.swing.JTextField();
        doTextField = new javax.swing.JTextField();
        datumTextField = new javax.swing.JTextField();
        odLabel = new javax.swing.JLabel();
        doLabel = new javax.swing.JLabel();
        datumLabel = new javax.swing.JLabel();
        zakaznikLabel = new javax.swing.JLabel();
        instruktorLabel = new javax.swing.JLabel();
        formatDatumuLabel = new javax.swing.JLabel();
        spatButton = new javax.swing.JButton();
        pridatHodinuButton = new javax.swing.JButton();
        zakaznikComboBox = new javax.swing.JComboBox<>();
        instruktorComboBox = new javax.swing.JComboBox<>();
        typLabel = new javax.swing.JLabel();
        typTextField = new javax.swing.JTextField();
        oduceneHodinyTextField = new javax.swing.JTextField();
        oduceneHodinyButton = new javax.swing.JButton();
        hodinyInstruktoraButton = new javax.swing.JButton();
        editInstruktorComboBox = new javax.swing.JComboBox<>();
        oduceneInstruktTextField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAutoRequestFocus(false);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setLocation(new java.awt.Point(300, 150));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(odTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 30, 100, -1));
        getContentPane().add(doTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 90, 100, -1));
        getContentPane().add(datumTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 30, 100, -1));

        odLabel.setText("*Od : ");
        getContentPane().add(odLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 30, -1, -1));

        doLabel.setText("*Do : ");
        getContentPane().add(doLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 90, -1, -1));

        datumLabel.setText("*Dátum  : ");
        getContentPane().add(datumLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, 60, -1));

        zakaznikLabel.setText("*Zákazník :");
        getContentPane().add(zakaznikLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, 70, -1));

        instruktorLabel.setText("*Inštruktor : ");
        getContentPane().add(instruktorLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 90, -1, -1));

        formatDatumuLabel.setText("(\"yyyy-MM-dd\")");
        getContentPane().add(formatDatumuLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, -1, 19));

        spatButton.setText("Späť");
        spatButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                spatButtonActionPerformed(evt);
            }
        });
        getContentPane().add(spatButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(467, 137, 133, -1));

        pridatHodinuButton.setText("Pridať hodinu");
        pridatHodinuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pridatHodinuButtonActionPerformed(evt);
            }
        });
        getContentPane().add(pridatHodinuButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 137, 163, -1));

        zakaznikComboBox.setModel(new ZakaznikComboBoxModel());
        zakaznikComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zakaznikComboBoxActionPerformed(evt);
            }
        });
        getContentPane().add(zakaznikComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 90, 100, -1));

        instruktorComboBox.setModel(new InstruktorComboBoxModel());
        getContentPane().add(instruktorComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 90, 100, -1));

        typLabel.setText("*Typ :");
        getContentPane().add(typLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 30, -1, 20));
        getContentPane().add(typTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 30, 100, -1));

        oduceneHodinyTextField.setEditable(false);
        getContentPane().add(oduceneHodinyTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(108, 259, 100, -1));

        oduceneHodinyButton.setText("Počet odučených hodín");
        oduceneHodinyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oduceneHodinyButtonActionPerformed(evt);
            }
        });
        getContentPane().add(oduceneHodinyButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 218, 163, -1));

        hodinyInstruktoraButton.setText("Počet odučených hodín Inštruktora");
        hodinyInstruktoraButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hodinyInstruktoraButtonActionPerformed(evt);
            }
        });
        getContentPane().add(hodinyInstruktoraButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(316, 218, 284, -1));

        editInstruktorComboBox.setModel(new InstruktorComboBoxModel());
        getContentPane().add(editInstruktorComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(316, 259, 100, -1));
        getContentPane().add(oduceneInstruktTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 259, 100, -1));

        jLabel1.setText("-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 184, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Silvia\\Desktop\\obrazky NETBeans\\vyucba.jpg")); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 400));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void spatButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_spatButtonActionPerformed
        this.dispose();
        uvodnyPanel.setVisible(true);
    }//GEN-LAST:event_spatButtonActionPerformed

    private void zakaznikComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zakaznikComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_zakaznikComboBoxActionPerformed

    private void pridatHodinuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pridatHodinuButtonActionPerformed
        Hodina hodina = new Hodina();
        boolean spravnost;
        Date datum;
        java.sql.Time casOd = null;
        java.sql.Time casDo = null;
        DateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        DateFormat timeFormat = new SimpleDateFormat("HH:mm");
        String date = datumTextField.getText();
        String od = odTextField.getText();
        String po = doTextField.getText();
        try {
            datum = dateFormat.parse(date);
            casOd = new java.sql.Time(timeFormat.parse(od).getTime());
            casDo = new java.sql.Time(timeFormat.parse(po).getTime());
            spravnost = true;
        } catch (ParseException e) {
           spravnost = false;
        }
        if(spravnost){
          if(kontrolaDatumu(date) && kontrolaCasu(od) && kontrolaCasu(po)){
            Instruktor instruktor = (Instruktor)instruktorComboBox.getSelectedItem();
            List<Long> obsadenost = hodinaDao.obsadenost(datumTextField.getText(), casOd, casDo,instruktor.getId());
            if(obsadenost.isEmpty()){
              hodina.setDatum(datumTextField.getText());
              hodina.setOd(casOd);
              hodina.setPo(casDo);
              hodina.setInstruktor(instruktor);
              hodina.setZakaznik((Zakaznik) zakaznikComboBox.getSelectedItem());
              hodina.setTyp(typTextField.getText());

              hodinaDao.pridajHodinu(hodina);
            }else{
              VynimkaObsadenostDialog vynimkaO = new VynimkaObsadenostDialog(this, true);
              vynimkaO.setVisible(true);
            }
          }else{
              NespravneUdajeDialog vynimka = new NespravneUdajeDialog(this, true);
              vynimka.setVisible(true);
          }
        }else{
           NespravneUdajeDialog vynimka = new NespravneUdajeDialog(this, true);
           vynimka.setVisible(true);
          
        }
        this.dispose();
        uvodnyPanel.setVisible(true);
    }//GEN-LAST:event_pridatHodinuButtonActionPerformed

    private void oduceneHodinyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oduceneHodinyButtonActionPerformed
        Long vystup = hodinaDao.oduceneHodiny();
        String odpoved = vystup.toString();
        oduceneHodinyTextField.setText(odpoved);
    }//GEN-LAST:event_oduceneHodinyButtonActionPerformed

    private void hodinyInstruktoraButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hodinyInstruktoraButtonActionPerformed
        Instruktor instruktor = (Instruktor) editInstruktorComboBox.getSelectedItem();
        Long hodiny = hodinaDao.oduceneInstruktHodiny(instruktor);
        oduceneInstruktTextField.setText(hodiny.toString());
    }//GEN-LAST:event_hodinyInstruktoraButtonActionPerformed

   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel datumLabel;
    private javax.swing.JTextField datumTextField;
    private javax.swing.JLabel doLabel;
    private javax.swing.JTextField doTextField;
    private javax.swing.JComboBox<Instruktor> editInstruktorComboBox;
    private javax.swing.JLabel formatDatumuLabel;
    private javax.swing.JButton hodinyInstruktoraButton;
    private javax.swing.JComboBox<Instruktor> instruktorComboBox;
    private javax.swing.JLabel instruktorLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel odLabel;
    private javax.swing.JTextField odTextField;
    private javax.swing.JButton oduceneHodinyButton;
    private javax.swing.JTextField oduceneHodinyTextField;
    private javax.swing.JTextField oduceneInstruktTextField;
    private javax.swing.JButton pridatHodinuButton;
    private javax.swing.JButton spatButton;
    private javax.swing.JLabel typLabel;
    private javax.swing.JTextField typTextField;
    private javax.swing.JComboBox<Zakaznik> zakaznikComboBox;
    private javax.swing.JLabel zakaznikLabel;
    // End of variables declaration//GEN-END:variables
}
