package Form;

import Form.ObsadenyZakaznikDialog;
import Form.PridatZakaznika;
import Dao.ZakaznikDao;
import com.sun.javafx.scene.control.SelectedCellsMap;
import sk.upjs.ics.lyz_skola.ObjectFactory;

public class ZakazniciForm extends javax.swing.JFrame {

    private UvodnyPanelForm uvodnyPanel;
    private ZakaznikDao zakaznikDao = ObjectFactory.INSTANCE.getZakaznikDao();
    private Integer vstupZoznam;
    private String priezvisko = null;
    private Integer telefon = 0;
    private Long id = -1L;
    
    public ZakazniciForm() {
        
    }
    
    public ZakazniciForm(UvodnyPanelForm uvodnyPanel){
        initComponents();
        this.uvodnyPanel = uvodnyPanel;
        vstupZoznam = 0;
        this.aktualizovatZoznam();
    }
    
    private void aktualizovatZoznam(){
        ZakazniciTableModel zakazniciModel = (ZakazniciTableModel) zakaznikTable.getModel();
        zakazniciModel.aktualizovat(vstupZoznam,priezvisko,telefon,id);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        zakaznikTable = new javax.swing.JTable();
        pridatZakaznikaButton = new javax.swing.JButton();
        spatButton = new javax.swing.JButton();
        podlaPriezviskaButton = new javax.swing.JButton();
        podlaIDButton = new javax.swing.JButton();
        zoraditLabel = new javax.swing.JLabel();
        filterLabel = new javax.swing.JLabel();
        priezviskoTextField = new javax.swing.JTextField();
        telefonFilterTextField = new javax.swing.JTextField();
        hladajPriezviskoButton = new javax.swing.JButton();
        hladajTelefonButton = new javax.swing.JButton();
        editaciaLabel = new javax.swing.JLabel();
        poznamkaLabel = new javax.swing.JLabel();
        poznamkaTextField = new javax.swing.JTextField();
        telefonLabel = new javax.swing.JLabel();
        telefonEditTextField = new javax.swing.JTextField();
        editButton = new javax.swing.JButton();
        vymazButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(300, 150));
        setPreferredSize(new java.awt.Dimension(730, 420));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        zakaznikTable.setModel(new ZakazniciTableModel());
        zakaznikTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                zakaznikTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(zakaznikTable);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(139, 11, 572, 206));

        pridatZakaznikaButton.setText("Pridať Zákazníka");
        pridatZakaznikaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pridatZakaznikaButtonActionPerformed(evt);
            }
        });
        getContentPane().add(pridatZakaznikaButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 32, -1, -1));

        spatButton.setText("Späť");
        spatButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                spatButtonActionPerformed(evt);
            }
        });
        getContentPane().add(spatButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 73, 111, -1));

        podlaPriezviskaButton.setText("Podľa Priezviska");
        podlaPriezviskaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                podlaPriezviskaButtonActionPerformed(evt);
            }
        });
        getContentPane().add(podlaPriezviskaButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, -1, -1));

        podlaIDButton.setText("Podľa ID");
        podlaIDButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                podlaIDButtonActionPerformed(evt);
            }
        });
        getContentPane().add(podlaIDButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 194, 111, -1));

        zoraditLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        zoraditLabel.setText("Zoradiť :");
        zoraditLabel.setToolTipText("");
        zoraditLabel.setIconTextGap(6);
        getContentPane().add(zoraditLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 111, -1));

        filterLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        filterLabel.setText("Filter : ");
        filterLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(filterLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 267, 111, -1));

        priezviskoTextField.setText("Priezvisko");
        priezviskoTextField.setToolTipText("");
        priezviskoTextField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                priezviskoTextFieldMouseClicked(evt);
            }
        });
        getContentPane().add(priezviskoTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 111, -1));

        telefonFilterTextField.setText("Telefon");
        telefonFilterTextField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                telefonFilterTextFieldMouseClicked(evt);
            }
        });
        getContentPane().add(telefonFilterTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 328, 111, -1));

        hladajPriezviskoButton.setText("Hľadaj");
        hladajPriezviskoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hladajPriezviskoButtonActionPerformed(evt);
            }
        });
        getContentPane().add(hladajPriezviskoButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(139, 287, -1, -1));

        hladajTelefonButton.setText("Hľadaj");
        hladajTelefonButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hladajTelefonButtonActionPerformed(evt);
            }
        });
        getContentPane().add(hladajTelefonButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(139, 325, -1, -1));

        editaciaLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        editaciaLabel.setText("Editácia/Zmazanie podľa výberu v tabuľke");
        getContentPane().add(editaciaLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(381, 267, 330, -1));

        poznamkaLabel.setText("Poznámka :");
        getContentPane().add(poznamkaLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 290, -1, -1));
        getContentPane().add(poznamkaTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(473, 287, 238, -1));

        telefonLabel.setText("Telefón :");
        getContentPane().add(telefonLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(412, 329, -1, -1));
        getContentPane().add(telefonEditTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(473, 326, 238, -1));

        editButton.setText("Editácia");
        editButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editButtonActionPerformed(evt);
            }
        });
        getContentPane().add(editButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(473, 366, -1, -1));

        vymazButton.setText("Vymazať Zákazníka");
        vymazButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vymazButtonActionPerformed(evt);
            }
        });
        getContentPane().add(vymazButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 366, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Silvia\\Desktop\\obrazky NETBeans\\zakaznici.jpg")); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 730, 400));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void spatButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_spatButtonActionPerformed
        this.dispose();
        uvodnyPanel.setVisible(true);
    }//GEN-LAST:event_spatButtonActionPerformed

    private void podlaPriezviskaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_podlaPriezviskaButtonActionPerformed
        vstupZoznam = 1;
        aktualizovatZoznam();
    }//GEN-LAST:event_podlaPriezviskaButtonActionPerformed

    private void podlaIDButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_podlaIDButtonActionPerformed
        vstupZoznam = 0;
        aktualizovatZoznam();
    }//GEN-LAST:event_podlaIDButtonActionPerformed

    private void priezviskoTextFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_priezviskoTextFieldMouseClicked
        if(priezviskoTextField.getText().equals("Priezvisko")){
            priezviskoTextField.setText("");
        }
    }//GEN-LAST:event_priezviskoTextFieldMouseClicked

    private void telefonFilterTextFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_telefonFilterTextFieldMouseClicked
        if(telefonFilterTextField.getText().equals("Telefon")){
            telefonFilterTextField.setText("");
        }
    }//GEN-LAST:event_telefonFilterTextFieldMouseClicked

    private void hladajPriezviskoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hladajPriezviskoButtonActionPerformed
        priezvisko = priezviskoTextField.getText();
        vstupZoznam = 2;
        aktualizovatZoznam();
    }//GEN-LAST:event_hladajPriezviskoButtonActionPerformed

    private void hladajTelefonButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hladajTelefonButtonActionPerformed
        String tel = telefonFilterTextField.getText();
        try {
            telefon = Integer.parseInt(tel);
            vstupZoznam = 3;
            aktualizovatZoznam();
        } catch (Exception e) {
            NespravneUdajeDialog nespravnyUdaj = new NespravneUdajeDialog(this, true);
            nespravnyUdaj.setVisible(true);
        }
        
    }//GEN-LAST:event_hladajTelefonButtonActionPerformed

    private void editButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editButtonActionPerformed
        if(id != -1L){
            try {
                if(!telefonEditTextField.getText().equals("")){
                    telefon = Integer.parseInt(telefonEditTextField.getText());
                    zakaznikDao.aktualizujTelefon(telefon, id);
                }
                if(!poznamkaTextField.getText().equals("")){
                    String poznamka = poznamkaTextField.getText();
                    zakaznikDao.aktualizujPoznamka(poznamka, id);
                }
                vstupZoznam = 4;
                aktualizovatZoznam();
            } catch (Exception e) {
                NespravneUdajeDialog nespravnyUdaj = new NespravneUdajeDialog(this, true);
                nespravnyUdaj.setVisible(true);
            }
            
        }else{
            NespravneUdajeDialog nespravnyUdaj = new NespravneUdajeDialog(this, true);
            nespravnyUdaj.setVisible(true);   
        }
        id = -1L;
    }//GEN-LAST:event_editButtonActionPerformed

    private void vymazButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vymazButtonActionPerformed
        if(id != -1L){
            if(zakaznikDao.nemaHodinu(id)){
                zakaznikDao.vymazZakaznika(id);
                vstupZoznam = 0;
                this.aktualizovatZoznam();
            }else{
            ObsadenyZakaznikDialog obsadeny = new ObsadenyZakaznikDialog(this, true);
            obsadeny.setVisible(true);
            }
        }
        id = -1L;
    }//GEN-LAST:event_vymazButtonActionPerformed
    
   
    private void pridatZakaznikaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pridatZakaznikaButtonActionPerformed
        PridatZakaznika pridatZakaznika = new PridatZakaznika(this, true);
        pridatZakaznika.setVisible(true);
        vstupZoznam = 0;
        this.aktualizovatZoznam();
    }//GEN-LAST:event_pridatZakaznikaButtonActionPerformed

    private void zakaznikTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_zakaznikTableMouseClicked
       id = (Long) zakaznikTable.getModel().getValueAt(zakaznikTable.getSelectedRow(), 0);               
    }//GEN-LAST:event_zakaznikTableMouseClicked

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton editButton;
    private javax.swing.JLabel editaciaLabel;
    private javax.swing.JLabel filterLabel;
    private javax.swing.JButton hladajPriezviskoButton;
    private javax.swing.JButton hladajTelefonButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton podlaIDButton;
    private javax.swing.JButton podlaPriezviskaButton;
    private javax.swing.JLabel poznamkaLabel;
    private javax.swing.JTextField poznamkaTextField;
    private javax.swing.JButton pridatZakaznikaButton;
    private javax.swing.JTextField priezviskoTextField;
    private javax.swing.JButton spatButton;
    private javax.swing.JTextField telefonEditTextField;
    private javax.swing.JTextField telefonFilterTextField;
    private javax.swing.JLabel telefonLabel;
    private javax.swing.JButton vymazButton;
    private javax.swing.JTable zakaznikTable;
    private javax.swing.JLabel zoraditLabel;
    // End of variables declaration//GEN-END:variables
}
