package sk.upjs.ics.lyz_skola;

import javax.swing.ImageIcon;

public class InstruktoriForm extends javax.swing.JFrame {

    private UvodnyPanelForm uvodnyPanel;
    private InstruktorDao instruktorDao = ObjectFactory.INSTANCE.getInstruktorDao();  
    private Integer vstupZoznam;
    private String priezvisko = null;
    private String akreditacia = null;
    private String typ = null;
    
    public InstruktoriForm() {
        
    }
    
    public InstruktoriForm(UvodnyPanelForm uvodnyPanel){
        initComponents();
        this.uvodnyPanel = uvodnyPanel;
        vstupZoznam = 0;
        this.aktualizovatZoznam();
    }
    
    private void aktualizovatZoznam(){
        InstruktoriTableModel instruktoriModel = (InstruktoriTableModel) instruktoriTable.getModel();
        instruktoriModel.aktualizovat(vstupZoznam, priezvisko, akreditacia, typ);
    }  

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        instruktoriTable = new javax.swing.JTable();
        spatButton = new javax.swing.JButton();
        zoradPodlaPriezviskaButton = new javax.swing.JButton();
        zadajAkreditaciuLabel = new javax.swing.JLabel();
        vypisPodlaAkreditacieButton = new javax.swing.JButton();
        zadajTypLabel = new javax.swing.JLabel();
        vypisPodlaTypuButton = new javax.swing.JButton();
        pridatInstruktoraButton = new javax.swing.JButton();
        akreditaciaComboBox = new javax.swing.JComboBox<>();
        typComboBox = new javax.swing.JComboBox<>();
        vypisPodlaPriezviskaButton = new javax.swing.JButton();
        priezviskoTextField = new javax.swing.JTextField();
        zadajPriezviskoLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setForeground(java.awt.Color.white);
        setPreferredSize(new java.awt.Dimension(849, 360));

        instruktoriTable.setModel(new InstruktoriTableModel());
        jScrollPane1.setViewportView(instruktoriTable);

        spatButton.setBackground(new java.awt.Color(0, 0, 255));
        spatButton.setForeground(new java.awt.Color(255, 255, 255));
        spatButton.setText("Späť");
        spatButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                spatButtonActionPerformed(evt);
            }
        });

        zoradPodlaPriezviskaButton.setBackground(new java.awt.Color(0, 0, 255));
        zoradPodlaPriezviskaButton.setForeground(new java.awt.Color(255, 255, 255));
        zoradPodlaPriezviskaButton.setText("Zoraď podľa priezviska");
        zoradPodlaPriezviskaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zoradPodlaPriezviskaButtonActionPerformed(evt);
            }
        });

        zadajAkreditaciuLabel.setText("Zadaj akreditáciu:");

        vypisPodlaAkreditacieButton.setBackground(new java.awt.Color(0, 0, 255));
        vypisPodlaAkreditacieButton.setForeground(new java.awt.Color(255, 255, 255));
        vypisPodlaAkreditacieButton.setText("Vypíš podľa akreditácie");
        vypisPodlaAkreditacieButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vypisPodlaAkreditacieButtonActionPerformed(evt);
            }
        });

        zadajTypLabel.setText("            Zadaj typ:");

        vypisPodlaTypuButton.setBackground(new java.awt.Color(0, 0, 255));
        vypisPodlaTypuButton.setForeground(new java.awt.Color(255, 255, 255));
        vypisPodlaTypuButton.setText("Vypíš podľa typu");
        vypisPodlaTypuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vypisPodlaTypuButtonActionPerformed(evt);
            }
        });

        pridatInstruktoraButton.setText("Pridaj inštruktora");
        pridatInstruktoraButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pridatInstruktoraButtonActionPerformed(evt);
            }
        });

        akreditaciaComboBox.setBackground(new java.awt.Color(0, 0, 255));
        akreditaciaComboBox.setForeground(new java.awt.Color(255, 255, 255));
        akreditaciaComboBox.setModel(new AkreditaciaComboBoxModel());

        typComboBox.setBackground(new java.awt.Color(0, 0, 255));
        typComboBox.setForeground(new java.awt.Color(255, 255, 255));
        typComboBox.setModel(new TypComboBoxModel());

        vypisPodlaPriezviskaButton.setBackground(new java.awt.Color(0, 0, 255));
        vypisPodlaPriezviskaButton.setForeground(new java.awt.Color(255, 255, 255));
        vypisPodlaPriezviskaButton.setText("Vypíš podľa priezviska");
        vypisPodlaPriezviskaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vypisPodlaPriezviskaButtonActionPerformed(evt);
            }
        });

        priezviskoTextField.setBackground(new java.awt.Color(0, 0, 255));
        priezviskoTextField.setForeground(new java.awt.Color(255, 255, 255));
        priezviskoTextField.setText("Priezvisko");
        priezviskoTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                priezviskoTextFieldActionPerformed(evt);
            }
        });

        zadajPriezviskoLabel.setText("  Zadaj priezvisko:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(vypisPodlaAkreditacieButton)
                    .addComponent(vypisPodlaPriezviskaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(127, 127, 127)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(spatButton, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addComponent(vypisPodlaTypuButton, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addComponent(akreditaciaComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addComponent(typComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(zadajTypLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(180, 180, 180)
                .addComponent(pridatInstruktoraButton, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addComponent(priezviskoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(zadajPriezviskoLabel))
            .addGroup(layout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addComponent(zoradPodlaPriezviskaButton))
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(zadajAkreditaciuLabel))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(vypisPodlaAkreditacieButton)
                .addGap(137, 137, 137)
                .addComponent(vypisPodlaPriezviskaButton))
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(400, 400, 400)
                .addComponent(spatButton))
            .addGroup(layout.createSequentialGroup()
                .addGap(130, 130, 130)
                .addComponent(vypisPodlaTypuButton))
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(akreditaciaComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addComponent(typComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addComponent(zadajTypLabel))
            .addGroup(layout.createSequentialGroup()
                .addGap(400, 400, 400)
                .addComponent(pridatInstruktoraButton))
            .addGroup(layout.createSequentialGroup()
                .addGap(170, 170, 170)
                .addComponent(priezviskoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(170, 170, 170)
                .addComponent(zadajPriezviskoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(270, 270, 270)
                .addComponent(zoradPodlaPriezviskaButton))
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(zadajAkreditaciuLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void spatButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_spatButtonActionPerformed
        this.dispose();
        uvodnyPanel.setVisible(true);
    }//GEN-LAST:event_spatButtonActionPerformed

    private void pridatInstruktoraButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pridatInstruktoraButtonActionPerformed
        PridatInstruktoraDialog pridatInstruktoraDialog = new PridatInstruktoraDialog(this, true);
        pridatInstruktoraDialog.setVisible(true);
        vstupZoznam = 0;
        aktualizovatZoznam();
    }//GEN-LAST:event_pridatInstruktoraButtonActionPerformed

    private void zoradPodlaPriezviskaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zoradPodlaPriezviskaButtonActionPerformed
        vstupZoznam = 1;
        aktualizovatZoznam();
    }//GEN-LAST:event_zoradPodlaPriezviskaButtonActionPerformed

    private void vypisPodlaTypuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vypisPodlaTypuButtonActionPerformed
        // TODO add your handling code here:
        typ = (String) typComboBox.getSelectedItem();
        vstupZoznam = 4;
        aktualizovatZoznam();
        
    }//GEN-LAST:event_vypisPodlaTypuButtonActionPerformed

    private void vypisPodlaAkreditacieButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vypisPodlaAkreditacieButtonActionPerformed
        // TODO add your handling code here:
        akreditacia = (String) akreditaciaComboBox.getSelectedItem();
        vstupZoznam = 3;
        aktualizovatZoznam();
    }//GEN-LAST:event_vypisPodlaAkreditacieButtonActionPerformed

    private void vypisPodlaPriezviskaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vypisPodlaPriezviskaButtonActionPerformed
        priezvisko = priezviskoTextField.getText();
        vstupZoznam = 2;
        aktualizovatZoznam();
    }//GEN-LAST:event_vypisPodlaPriezviskaButtonActionPerformed

    private void priezviskoTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_priezviskoTextFieldActionPerformed
        if(priezviskoTextField.getText().equals("Priezvisko")){
            priezviskoTextField.setText("");
        }
    }//GEN-LAST:event_priezviskoTextFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InstruktoriForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InstruktoriForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InstruktoriForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InstruktoriForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InstruktoriForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> akreditaciaComboBox;
    private javax.swing.JTable instruktoriTable;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton pridatInstruktoraButton;
    private javax.swing.JTextField priezviskoTextField;
    private javax.swing.JButton spatButton;
    private javax.swing.JComboBox<String> typComboBox;
    private javax.swing.JButton vypisPodlaAkreditacieButton;
    private javax.swing.JButton vypisPodlaPriezviskaButton;
    private javax.swing.JButton vypisPodlaTypuButton;
    private javax.swing.JLabel zadajAkreditaciuLabel;
    private javax.swing.JLabel zadajPriezviskoLabel;
    private javax.swing.JLabel zadajTypLabel;
    private javax.swing.JButton zoradPodlaPriezviskaButton;
    // End of variables declaration//GEN-END:variables
}
