package sk.upjs.ics.lyz_skola;

import java.awt.Color;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Scanner;
import javax.swing.table.DefaultTableCellRenderer;
import org.springframework.security.crypto.bcrypt.BCrypt;
import sun.swing.table.DefaultTableCellHeaderRenderer;

public class UvodnyPanelForm extends javax.swing.JFrame {
    
    private String nastavenyDatum;
    private Long id = -1L;
    private HodinaDao hodinaDao = ObjectFactory.INSTANCE.getHodinaDao();

    public UvodnyPanelForm() {
        initComponents();
        nastavenyDatum = null;
        aktualizovatUvodnyPanel();
        
        
    }
    private void aktualizovatUvodnyPanel() {
        HodinyTableModel model = (HodinyTableModel) hodinyTable.getModel();                
        model.aktualizovat(nastavenyDatum);
    }
    
    private boolean kontrolaDatumu(String datum){
        boolean vystup = true;
        Scanner scan = new Scanner(datum).useDelimiter("-");
        while(scan.hasNext()){
            if(scan.hasNextInt()){
		scan.next();
            }else{
		vystup = false;
		scan.next();
            }
	}
        scan.close();
        return vystup;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        hodinyTable = new javax.swing.JTable();
        datumButton = new javax.swing.JButton();
        datumTextField = new javax.swing.JTextField();
        formatDatumuLabel = new javax.swing.JLabel();
        vyucbaButton = new javax.swing.JButton();
        instruktoriButton = new javax.swing.JButton();
        zakazniciButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setFocusCycleRoot(false);
        setLocation(new java.awt.Point(308, 204));
        setLocationByPlatform(true);
        setMinimumSize(new java.awt.Dimension(780, 400));
        setResizable(false);
        setSize(new java.awt.Dimension(780, 400));

        hodinyTable.setModel(new HodinyTableModel());
        hodinyTable.setOpaque(false);
        jScrollPane1.setViewportView(hodinyTable);

        datumButton.setText("Nastavit");
        datumButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                datumButtonActionPerformed(evt);
            }
        });

        datumTextField.setText("Vloz datum");

        formatDatumuLabel.setBackground(java.awt.Color.darkGray);
        formatDatumuLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        formatDatumuLabel.setForeground(new java.awt.Color(255, 0, 0));
        formatDatumuLabel.setText("\"yyyy-MM-dd\"");
        formatDatumuLabel.setOpaque(true);

        vyucbaButton.setText("Výučba");
        vyucbaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vyucbaButtonActionPerformed(evt);
            }
        });

        instruktoriButton.setText("Inštruktori");
        instruktoriButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                instruktoriButtonActionPerformed(evt);
            }
        });

        zakazniciButton.setText("Zákazníci");
        zakazniciButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zakazniciButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(vyucbaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(instruktoriButton, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(zakazniciButton, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(datumButton, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(datumTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(formatDatumuLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 491, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(vyucbaButton)
                .addGap(18, 18, 18)
                .addComponent(instruktoriButton)
                .addGap(18, 18, 18)
                .addComponent(zakazniciButton)
                .addGap(135, 135, 135)
                .addComponent(datumButton))
            .addGroup(layout.createSequentialGroup()
                .addGap(300, 300, 300)
                .addComponent(datumTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(formatDatumuLabel))
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void datumButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_datumButtonActionPerformed
        nastavenyDatum = datumTextField.getText();
        boolean spravnost = true;
        Date datum;
        DateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        try {
            datum = dateFormat.parse(nastavenyDatum);
        } catch (Exception e) {
            spravnost = false;
        }
        if(spravnost){
            if(kontrolaDatumu(nastavenyDatum)){
                aktualizovatUvodnyPanel();
            }else{
                NespravneUdajeDialog vynimka = new NespravneUdajeDialog(this, true);
                vynimka.setVisible(true);
            }
        }else{
            NespravneUdajeDialog vynimka = new NespravneUdajeDialog(this, true);
            vynimka.setVisible(true);
        }
    }//GEN-LAST:event_datumButtonActionPerformed

    private void vyucbaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vyucbaButtonActionPerformed
        this.setVisible(false);
        VyucbaForm vyucbaForm = new VyucbaForm(this);
        vyucbaForm.setVisible(true);
        aktualizovatUvodnyPanel();
    }//GEN-LAST:event_vyucbaButtonActionPerformed

    private void instruktoriButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_instruktoriButtonActionPerformed
        this.setVisible(false);
        InstruktoriForm instruktoriForm = new InstruktoriForm(this);
        instruktoriForm.setVisible(true);
    }//GEN-LAST:event_instruktoriButtonActionPerformed

    private void zakazniciButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zakazniciButtonActionPerformed
        this.setVisible(false);
        ZakazniciForm zakazniciForm = new ZakazniciForm(this);
        zakazniciForm.setVisible(true);
    }//GEN-LAST:event_zakazniciButtonActionPerformed

   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton datumButton;
    private javax.swing.JTextField datumTextField;
    private javax.swing.JLabel formatDatumuLabel;
    private javax.swing.JTable hodinyTable;
    private javax.swing.JButton instruktoriButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton vyucbaButton;
    private javax.swing.JButton zakazniciButton;
    // End of variables declaration//GEN-END:variables

    
}
